# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

formatting:
  NoWildcardImports:
    active: false
  PackageName:
    active: false

empty-blocks:
  EmptyFunctionBlock:
    ignoreOverridden: true

style:
  MagicNumber:
    active: false
  WildcardImport:
    active: false

naming:
  PackageNaming:
    active: false
